apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  PORT: "3000"
  APP_NAME: "TaskFlow API"
  NODE_ENV: "production"
  APP_VERSION: "prod"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
