apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow-prod

resources:
  - ../../base

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: taskflow-ingress
    path: ingress-patch.yaml

  - target:
      version: v1
      kind: ConfigMap
      name: api-config
    path: api-configmap-patch.yaml

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: api
    path: api-deployment-patch.yaml

  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: api-hpa
    path: api-hpa-patch.yaml
