apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: "api"
    app.kubernetes.io/name: "taskflow"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  selector:
    app: "api"
  ports:
    - name: http
      port: !!int "{{ .Values.api.port }}"
      targetPort: !!int "{{ .Values.api.port }}"
