{{- if and .Values.postgresExporter.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  labels:
    release: "{{ .Values.serviceMonitor.releaseLabel }}"
    app.kubernetes.io/name: "taskflow"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: "postgres-exporter"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
{{- end }}
