apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 3000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
