apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "taskflow_user"
  POSTGRES_PASSWORD: "taskflow_password"
  POSTGRES_DB: "taskflow"
  DATABASE_URL: "postgresql://taskflow_user:taskflow_password@postgres-service:5432/taskflow"
