apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ArturPravdivtsev/taskflow-mini-saas.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: taskflow-prod

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
