apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - api-servicemonitor.yaml
  - api-prometheusrule.yaml
  - api-pdb.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - postgres-exporter-deployment.yaml
  - postgres-exporter-service.yaml
  - postgres-exporter-servicemonitor.yaml
