apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/arturpravdivtsev/taskflow-api:97b2a2e4ad9003342c158c829f9566fea1ccde34
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/arturpravdivtsev/taskflow-web:97b2a2e4ad9003342c158c829f9566fea1ccde34
