apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/arturpravdivtsev/taskflow-api:f6541817cecd946a05f17dfb7b642c3cdefea167
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/arturpravdivtsev/taskflow-web:f6541817cecd946a05f17dfb7b642c3cdefea167
