apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/arturpravdivtsev/taskflow-api:a8e36802acf31e1bce97fd5e525752bde1f333ea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/arturpravdivtsev/taskflow-web:a8e36802acf31e1bce97fd5e525752bde1f333ea
